# Generated by Django 3.2 on 2022-09-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={'verbose_name': 'Genre Filmwork', 'verbose_name_plural': 'Genres Filmworks'},
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={'verbose_name': 'Person Filmwork', 'verbose_name_plural': 'Persons Filmworks'},
        ),
        migrations.AddField(
            model_name='filmwork',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='movies/', verbose_name='file'),
        ),
    ]
