# Generated by Django 3.2 on 2022-09-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220928_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('actor', 'actor'), ('writer', 'writer'), ('director', 'director')], max_length=128, null=True, verbose_name='role'),
        ),
    ]
