version: '3'
services:
  service:
    build: app
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - postgres
    volumes:
      - data:/opt/app/data

  data-transfer:
    build: sqlite_to_postgres
    env_file:
      - .env
    depends_on:
      - service

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - data:/data/:ro
    depends_on:
      - service
    ports:
      - "80:80"

  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  etl:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    depends_on:
      - data-transfer
    environment:
      - discovery.type=single-node
    volumes:
      - etl_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  etl_transfer:
    build: etl
    depends_on:
      - data-transfer
    env_file:
      - .env
    volumes:
      - ./etl/state.json:/opt/etl/state.json


volumes:
  data:
  db_data:
  etl_data: